// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: User.sql

package database

import (
	"context"
)

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetAllUsers(ctx context.Context, id int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
