services:
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - ../.env  

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  